on:
  push:
    branches:
      - main
      # - "**"

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        node-version:
          - latest
        # - 16.x

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install NPM dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Linter
        run: pnpm lint

      - name: Run Tests
        run: pnpm test
